# Use Vault/Economy instead of having a separate place to store EMC?
# Requires Vault Plugin
economy: false

# Should items with custom lore be able to be transmuted?
# Can stop most custom item exploits, as they usually have lore.
lore: true