name: TransmuteIt
main: pw.chew.transmuteit.TransmuteIt
version: 0.2.0
api-version: 1.15
description: It's just ProjectE Transmutation for Spigot
author: Chewsterchew
website: https://github.com/Chew/TransmuteIt
softdepend: [Vault]
commands:
  transmute:
    description: The main command for the plugin.
    usage: "Usage: /transmute"
    permission: transmute.main
    permission-message: The admins have revoked your ability to run this command!
    default: true
  setEMC:
    description: Set the EMC value of the held item.
    usage: "Usage: /setEMC 8"
    permission: transmute.admin.emc.set
    permission-message: The admins have revoked your ability to run this command!
    default: op
  getEMC:
    description: Get the EMC value of the held item.
    usage: "Usage: /getEMC"
    permission: transmute.emc.get
    permission-message: The admins have revoked your ability to run this command!
    default: true
  emc:
    description: Get your EMC value.
    usage: "Usage: /emc"
    permission: transmute.player.emc
    permission-message: The admins have revoked your ability to run this command!
    default: true
  discoveries:
    description: Get your discoveries.
    usage: "Usage: /discoveries"
    permission: transmute.player.discoveries
    permission-message: The admins have revoked your ability to run this command!
    default: true

permissions:
  transmute.player:
    default: true
    children:
      transmute.main: true
      transmute.emc.get: true
      transmute.player.emc: true
      transmute.player.discoveries: true
  transmute.*:
    default: op
    children:
      transmute.admin.emc.set: true
      transmute.player: true
