name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release')"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package -Dbuild=${{ github.run_id }}
    - name: Copy Jar and Remove Bad Jars
      run: mkdir staging && rm target/original-* && rm target/*-jar-with-dependencies.jar && cp target/*.jar staging
    - name: Upload Jar
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    - name: Publish package
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        mvn --settings settings.xml deploy
